#!/usr/bin/env bash
#
# TexRec one-shot installer.
#   Clones the repo, prompts for configuration, writes .env, then builds
#   and starts the Docker stack (app + PostgreSQL).
#
# Run directly:                bash install.sh
# Or straight from GitHub:     curl -fsSL https://raw.githubusercontent.com/encondata/texrec/main/install.sh | bash
#
# Optional: set TEXREC_DIR to choose the install folder (default: ./texrec).

set -euo pipefail

REPO="https://github.com/encondata/texrec.git"
DIR="${TEXREC_DIR:-texrec}"
TTY=/dev/tty

# ---- pretty output -------------------------------------------------------
if [ -t 1 ]; then B=$'\033[1m'; R=$'\033[0;31m'; G=$'\033[0;32m'; Y=$'\033[0;33m'; N=$'\033[0m'
else B=""; R=""; G=""; Y=""; N=""; fi
say()  { printf '%s\n' "${B}$*${N}"; }
ok()   { printf '%s\n' "${G}✓ $*${N}"; }
warn() { printf '%s\n' "${Y}! $*${N}"; }
die()  { printf '%s\n' "${R}✗ $*${N}" >&2; exit 1; }

# ---- interactive input (reads from the terminal even when piped) ----------
[ -e "$TTY" ] || die "This installer needs an interactive terminal (couldn't open /dev/tty)."

# read a finite chunk so no stage gets SIGPIPE under `set -o pipefail`
gen_pw() { head -c 24 /dev/urandom | LC_ALL=C base64 | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-24; }

ask() { # ask VARNAME "Prompt" "default"
  local __v=$1 prompt=$2 default=$3 answer
  printf '%s [%s]: ' "$prompt" "$default" >"$TTY"
  IFS= read -r answer <"$TTY" || true
  printf -v "$__v" '%s' "${answer:-$default}"
}

ask_secret() { # ask_secret VARNAME "Prompt"   (blank => auto-generate)
  local __v=$1 prompt=$2 answer
  printf '%s (blank = auto-generate a strong one): ' "$prompt" >"$TTY"
  IFS= read -rs answer <"$TTY" || true
  printf '\n' >"$TTY"
  if [ -z "$answer" ]; then answer=$(gen_pw); printf '  %s\n' "${G}→ generated${N}" >"$TTY"; fi
  printf -v "$__v" '%s' "$answer"
}

# ---- prerequisites -------------------------------------------------------
say "TexRec installer"
command -v git >/dev/null 2>&1 || die "git is not installed."
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install Docker, then re-run."
docker info >/dev/null 2>&1 || die "Docker is installed but not running. Start Docker Desktop / the daemon, then re-run."
if docker compose version >/dev/null 2>&1; then DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then DC="docker-compose"
else die "Docker Compose is not available."; fi
ok "git + Docker ($DC) present"

# ---- get the code --------------------------------------------------------
if [ -d "$DIR/.git" ]; then
  say "Updating existing checkout in ./$DIR"
  git -C "$DIR" pull --ff-only
else
  say "Cloning $REPO -> ./$DIR"
  git clone --depth 1 "$REPO" "$DIR"
fi
cd "$DIR"
ok "code ready in $(pwd)"

# ---- configure -----------------------------------------------------------
if [ -f .env ]; then
  ask KEEP "An .env already exists here. Keep it and skip configuration? (y/n)" "y"
  case "$KEEP" in y|Y|yes|YES) SKIP_ENV=1;; *) SKIP_ENV=0;; esac
else
  SKIP_ENV=0
fi

if [ "$SKIP_ENV" = "0" ]; then
  say ""
  say "Configure TexRec  (press Enter to accept the [default])"
  ask        PGDATABASE            "  Database name"                    "texrec"
  ask        PGUSER                "  Database user"                    "texrec"
  ask_secret PGPASSWORD            "  Database password"
  ask        HOST_PORT             "  Port to serve the site on"       "80"
  ask        CORS_ORIGIN           "  Allowed origin(s) (* = any; use https://yourdomain.com in prod)" "*"
  ask        ADMIN_TOKEN_HOURS     "  Staff session lifetime (hours)"  "12"
  ask        CUSTOMER_TOKEN_DAYS   "  Customer session lifetime (days)" "7"
  ask        BOOTSTRAP_ADMIN_EMAIL "  First admin email"               "admin@texrec.com"
  ask_secret BOOTSTRAP_ADMIN_PASSWORD "  First admin password"
  ask        BOOTSTRAP_ADMIN_NAME  "  First admin display name"        "TexRec Admin"

  umask 077   # .env is written owner-only
  cat > .env <<EOF
# generated by install.sh — keep this file private
PGDATABASE=$PGDATABASE
PGUSER=$PGUSER
PGPASSWORD=$PGPASSWORD
HOST_PORT=$HOST_PORT
CORS_ORIGIN=$CORS_ORIGIN
ADMIN_TOKEN_HOURS=$ADMIN_TOKEN_HOURS
CUSTOMER_TOKEN_DAYS=$CUSTOMER_TOKEN_DAYS
BOOTSTRAP_ADMIN_EMAIL=$BOOTSTRAP_ADMIN_EMAIL
BOOTSTRAP_ADMIN_PASSWORD=$BOOTSTRAP_ADMIN_PASSWORD
BOOTSTRAP_ADMIN_NAME=$BOOTSTRAP_ADMIN_NAME
EOF
  ok ".env written (permissions 600)"
else
  # shellcheck disable=SC1091
  set -a; . ./.env; set +a
  ok "using existing .env"
fi

PORT="${HOST_PORT:-80}"

# ---- build & launch ------------------------------------------------------
say ""
say "Building the app image and pulling PostgreSQL…"
$DC up -d --build

say "Waiting for the site to come up…"
up=0
for _ in $(seq 1 45); do
  if curl -fsS "http://localhost:${PORT}/api/courses" >/dev/null 2>&1; then up=1; break; fi
  sleep 2
done

echo
if [ "$up" = "1" ]; then
  ok "TexRec is running."
  say  "  Site:         http://localhost:${PORT}"
  say  "  Admin portal: http://localhost:${PORT}/admin"
  say  "  Sign in with the first-admin email you set (change the password after first login)."
else
  warn "Containers started, but the site didn't answer on port ${PORT} yet."
  warn "Check logs with:  $DC logs -f app"
fi
echo
say "Manage it:"
printf '  %s logs -f app     # watch logs\n'        "$DC"
printf '  %s down            # stop (data kept)\n'   "$DC"
printf '  %s up -d --build   # update after a git pull\n' "$DC"
